// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_HXpGzwTbMkGBKZT8S_lmZa89oJbWdes',
    appId: '1:338048282243:web:1a561290bb9660417f75b6',
    messagingSenderId: '338048282243',
    projectId: 'flutterappdatabase-5bf2c',
    authDomain: 'flutterappdatabase-5bf2c.firebaseapp.com',
    databaseURL: 'https://flutterappdatabase-5bf2c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterappdatabase-5bf2c.appspot.com',
    measurementId: 'G-9D4NQB8HCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWvtSVr-uHZCUvw3JTFjJQEXWc3IeVQy4',
    appId: '1:338048282243:android:d1661bcdbe73c0e37f75b6',
    messagingSenderId: '338048282243',
    projectId: 'flutterappdatabase-5bf2c',
    databaseURL: 'https://flutterappdatabase-5bf2c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterappdatabase-5bf2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEpyi9QR0mSJQ-o9UdzXPATAK9zo6gzSQ',
    appId: '1:338048282243:ios:f56ed690707af60d7f75b6',
    messagingSenderId: '338048282243',
    projectId: 'flutterappdatabase-5bf2c',
    databaseURL: 'https://flutterappdatabase-5bf2c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterappdatabase-5bf2c.appspot.com',
    iosClientId: '338048282243-5ht1a80ip5r6b171cmm1qbps76mt3euu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEpyi9QR0mSJQ-o9UdzXPATAK9zo6gzSQ',
    appId: '1:338048282243:ios:f56ed690707af60d7f75b6',
    messagingSenderId: '338048282243',
    projectId: 'flutterappdatabase-5bf2c',
    databaseURL: 'https://flutterappdatabase-5bf2c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterappdatabase-5bf2c.appspot.com',
    iosClientId: '338048282243-5ht1a80ip5r6b171cmm1qbps76mt3euu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter_app',
  );
}
